require("kbreit.plugins-setup")
require("kbreit.core.options")
require("kbreit.core.keymaps")
require("kbreit.core.colorscheme")
require("kbreit.plugins.comment")
require("kbreit.plugins.nvim-tree")
require("kbreit.plugins.lualine")
require("kbreit.plugins.telescope")
require("kbreit.plugins.nvim-cmp")
require("kbreit.plugins.lsp.mason")
require("kbreit.plugins.lsp.lspsaga")
require("kbreit.plugins.lsp.lspconfig")
require("kbreit.plugins.lsp.null-ls")
require("kbreit.plugins.autopairs")
-- require("kbreit.plugins.treesitter")
require("kbreit.plugins.gitsigns")
