# Config file
preload = /home/kbreit/Documents/Wallpaper/373.png
preload = /home/kbreit/Documents/Wallpaper/374.jpeg
preload = /home/kbreit/Documents/Wallpaper/375.jpeg
preload = /home/kbreit/Documents/Wallpaper/376.jpeg
wallpaper = eDP-1,/home/kbreit/Documents/Wallpaper/373.png
splash = false
ipc = on
